# Generated by Django 3.2 on 2022-03-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('friendly_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('file', models.FileField(upload_to='uploads/files/')),
                ('demo_link', models.TextField(max_length=1000)),
                ('stripe_price_id', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.categories')),
            ],
        ),
    ]
