# Generated by Django 3.2 on 2022-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
