# Generated by Django 3.2 on 2022-03-21 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_packs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packs',
            name='file',
        ),
        migrations.AddField(
            model_name='packs',
            name='download_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
