# Generated by Django 3.2 on 2022-03-05 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_packs_demo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='stripe_price_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
