# Generated by Django 3.2 on 2022-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220315_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='user',
        ),
    ]
