# Generated by Django 3.2 on 2022-03-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreply',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contactsubmission'),
        ),
    ]
